rootless-containers/slirp4netns

Makefile
Makefile.am
README.md
autogen.sh
configure.ac
slirp.c

so we can do: ./configure && make && make install for installing the package

build: use GNU build system

---

README.md

README.md: document how to build a static binary

---

Makefile.am
main.c
slirp.c
slirp.h

if specified it tells slirp4netns what FD must be monitored for
events.  On an event on the FD the program exits with success.

slirp: add a new option -e FD

---

.travis.yml
Dockerfile.tests
Makefile.am
hack/indent.sh
main.c

fix issues found by clang-tidy

---

Dockerfile.tests
Makefile.am
README.md
benchmarks/benchmark-iperf3.sh
tests/common.sh

add iperf3 benchmark

---

Dockerfile.tests
Makefile.am
README.md
benchmarks/benchmark-iperf3.sh
configure.ac
main.c
qemu/slirp/dhcpv6.c
qemu/slirp/if.h
qemu/slirp/ip6_icmp.c
qemu/slirp/ip6_input.c
qemu/slirp/ip_output.c
qemu/slirp/libslirp.h
qemu/slirp/mbuf.c
qemu/slirp/slirp.c
qemu/slirp/slirp.h
qemu/slirp/tcp_input.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns-ready-fd.sh

https://github.com/rootless-containers/slirp4netns/issues/19
Benchmark will be executed on Travis
cc @giuseppe

allow custom MTU

---

qemu/slirp/mbuf.c

Cherry-pick qemu/qemu@09b94ac0f29db3b022a77a5aa50dc9e37032689d

Correct size check in m_inc()

---

main.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h

experimental support for ipv6

---

main.c
slirp4netns.1
slirp4netns.1.md

add --help

---

main.c

fix lint error

---

README.md

README.md: add SUSE

---

README.md

README.md: add more adopters

---

README.md

README.md: mention Debian package

---

tests/common.sh
tests/test-slirp4netns-ready-fd.sh

a couple of fixes that could help with a flaky test.

tests: fix flaky test

---

README.md

README.md: add new AUR package

---

Makefile.am
main.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns-cidr.sh

support specifying --cidr

---

Makefile.am
main.c
qemu/slirp/libslirp.h
qemu/slirp/slirp.c
qemu/slirp/slirp.h
qemu/slirp/socket.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns-disable-host-loopback.sh

--no-host-loopback -> --disable-host-loopback

---

Dockerfile.tests
api.c
api.h
slirp4netns.1.md
slirp4netns.c
tests/common.sh
tests/test-slirp4netns-api-socket.sh
tests/test-slirp4netns-disable-host-loopback.sh

a few different fixes for the port redirection feature.

api: fix some issues in the port redirection

---

configure.ac
qemu/slirp/tcp_subr.c

https://access.redhat.com/security/cve/cve-2019-6778
https://github.com/qemu/qemu/commit/a7104eda7dab99d0cdbd3595c211864cba415905

v0.2.1 (CVE-2019-6778)

---

MAINTAINERS
README.md
SECURITY_CONTACTS

@rootless-containers/slirp4netns-approvers 
@rootless-containers/slirp4netns-package-maintainers 
Close #69

update docs (including addition of MAINTAINERS)

---

slirp4netns.c

fix comment

---

.travis.yml
Dockerfile.buildtests

add Dockerfile.buildtests

---

qemu/README.md
qemu/slirp/src/socket.c
qemu_patches/sync.sh

sync qemu v4.0.0-rc4

---

.clang-format
Dockerfile.tests
Makefile.am
api.c
main.c
slirp4netns.c
vendor.sh
vendor/libslirp/.clang-format

[RFC] import .clang-format from libslirp

---

main.c

fix WIFEXITED regression

---

slirp4netns.1
slirp4netns.1.md

man: update

---

Dockerfile.buildtests
Makefile.am
configure.ac
main.c
sandbox.c
sandbox.h
slirp4netns.1
slirp4netns.1.md
slirp4netns.c

follow-up to #105 
fix #114 
cc @giuseppe

follow-up to #105

---

vendor_patches/libslirp/0001-add-slirp_initx-SlirpConfig-SlirpCb-void.patch
vendor_patches/libslirp/0002-allow-custom-MTU.patch
vendor_patches/libslirp/0003-add-disable_host_loopback-prohibit-connections-to-12.patch

Thanks @sthibaul for finding this issue https://gitlab.freedesktop.org/slirp/libslirp/merge_requests/8#note_197706

ip_icmp.c: fix use-after-free

---

vendor/README.md
vendor/libslirp/src/ip_icmp.c

reapply vendor_patches

---

Dockerfile.tests
configure.ac
qemu/slirp/tcp_subr.c

Cherry-pick https://github.com/qemu/qemu/commit/d3222975c7d6cda9e25809dea05241188457b113

[release/0.2] slirp: check sscanf result when emulating ident (v0.2.2)

---

configure.ac
qemu/slirp/ip_input.c

Cherry-pick https://gitlab.freedesktop.org/slirp/libslirp/commit/126c04acbabd7ad32c2b018fe10dfac2a3bc1210

[release/0.2] slirp: Fix heap overflow in ip_reass on big packet input (v0.2.3)

---

main.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns.sh

Closes: https://github.com/rootless-containers/slirp4netns/issues/136

slirp4netns: rename --create-sandbox to --enable-sandbox

---

Dockerfile.buildtests
Dockerfile.tests
Makefile.am
README.md
configure.ac
main.c
seccompfilter.c
seccompfilter.h
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h

add --enable-seccomp

---

vendor.sh
vendor/README.md
vendor/libslirp/src/ip_input.c

https://gitlab.freedesktop.org/slirp/libslirp/compare/76462e2f16c6fce6856fb914cbef6207d0be4bc5...d203c81bc6c861e1671122c3194c21d1a6763641

vendor libslirp@d203c81bc6c861e1671122c3194c21d1a6763641

---

vendor.sh
vendor/README.md
vendor/libslirp/src/ip_input.c

https://gitlab.freedesktop.org/slirp/libslirp/compare/76462e2f16c6fce6856fb914cbef6207d0be4bc5...d203c81bc6c861e1671122c3194c21d1a6763641
(cherry picked from commit fc63e79b99ee646d15663592a42a672a5b2d0126)

[release/0.3] vendor libslirp@d203c81bc6c861e1671122c3194c21d1a6763641

---

README.md

@rootless-containers/slirp4netns-approvers @rootless-containers/slirp4netns-package-maintainers RFC

[RFC] README.md: add maintenance policy

---

Dockerfile.buildtests
Makefile.am

Makefile.am: fix AM_CFLAGS

---

vendor.sh
vendor/README.md
vendor/libslirp/src/arp_table.c
vendor/libslirp/src/dnssearch.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/sbuf.c
vendor/libslirp/src/sbuf.h
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/state.c
vendor/libslirp/src/tcp_input.c
vendor/libslirp/src/tcp_subr.c
vendor/libslirp/src/vmstate.c

https://gitlab.freedesktop.org/slirp/libslirp/compare/d171af3732a0610a25334b06b77fa547bd677918...6651ba26c4e94f64d6448a2db4991269ce553bd9

vendor libslirp v4.1.0

---

configure.ac
vendor.sh
vendor/README.md
vendor/libslirp/src/arp_table.c
vendor/libslirp/src/dnssearch.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/misc.c
vendor/libslirp/src/sbuf.c
vendor/libslirp/src/sbuf.h
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/state.c
vendor/libslirp/src/tcp_input.c
vendor/libslirp/src/tcp_subr.c
vendor/libslirp/src/vmstate.c

https://gitlab.freedesktop.org/slirp/libslirp/compare/d203c81bc6c861e1671122c3194c21d1a6763641...6651ba26c4e94f64d6448a2db4991269ce553bd9
Cherry-pick #164

[release/0.3] vendor libslirp v4.1.0  (release slirp4netns v0.3.4)

---

MAINTAINERS

MAINTAINERS: document release process

---

.github/workflows/main.yaml
Dockerfile.buildtests
Dockerfile.tests

Dockerfile.*: support build-arg LIBSLIRP_COMMIT

---

configure.ac
main.c
vendor.sh
vendor/README.md
vendor/libslirp/src/bootp.c
vendor/libslirp/src/bootp.h
vendor/libslirp/src/dhcpv6.c
vendor/libslirp/src/ip_icmp.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/libslirp.h
vendor/libslirp/src/misc.c
vendor/libslirp/src/misc.h
vendor/libslirp/src/ncsi.c
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/state.c
vendor/libslirp/src/tcp_subr.c
vendor/libslirp/src/tftp.c
vendor/libslirp/src/udp.c
vendor/libslirp/src/util.c
vendor/libslirp/src/util.h
vendor/parson/parson.c
vendor/parson/parson.h

Notable changes since v0.4.3:
* libslirp: update to v4.2.0: https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.2.0/CHANGELOG.md

[release/0.4] vendor libslirp v4.2.0 (release slirp4netns v0.4.4) 

---

README.md

#176 
@rootless-containers/slirp4netns-approvers @rootless-containers/slirp4netns-package-maintainers  PTAL

set v0.3 EOL to Mar 31, 2020; set v0.4 EOL to Sep 30, 2020

---

main.c
slirp4netns.1
slirp4netns.1.md

move --enable-sandbox out of experimental

---

configure.ac
vendor.sh
vendor/README.md
vendor/libslirp/src/ip_input.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/libslirp.h
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/version.c

https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.3.0/CHANGELOG.md

v0.4.5 (libslirp v4.3.0)

---

configure.ac
vendor.sh
vendor/README.md
vendor/libslirp/src/arp_table.c
vendor/libslirp/src/dnssearch.c
vendor/libslirp/src/ip6_icmp.c
vendor/libslirp/src/ip6_input.c
vendor/libslirp/src/ip_icmp.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/ncsi.c
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/tftp.c
vendor/libslirp/src/tftp.h
vendor/libslirp/src/udp.c
vendor/libslirp/src/util.c

https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.3.1/CHANGELOG.md

v0.4.7 (libslirp v4.3.1)

---

.github/workflows/release.yaml
configure.ac

The release pipeline for v1.1.5 failed due to this typo :(

CI: fix a typo in release.yaml 

---

Makefile.am
seccompfilter.c
seccompfilter_rules.h

seccomp: block more syscalls

---

.github/workflows/release.yaml

https://github.com/overmindtech/buildkit-cache-dance is no longer maintained

overmindtech/buildkit-cache-dance -> reproducible-containers/buildkit-cache-dance

---

.github/workflows/main.yaml
Dockerfile.artifact
Dockerfile.buildtests
Dockerfile.tests
configure.ac

https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.8.0/CHANGELOG.md

CI: bump libslirp to v4.8.0
