Makefile.am
main.c
slirp4netns.1
slirp4netns.1.md
tests/test-slirp4netns-ready-fd.sh

There is a race now where it is not possible to know when the network
namespace is configured, unless the caller polls for the new device to
be up.
Add a new function to immediately notify the caller when the network
is configured.

slirp4netns: add -r FD

---

COPYING

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
This solves an rpmlint error (incorrect-fsf-address)
@giuseppe @AkihiroSuda @cyphar

correct FSF address

---

slirp4netns.c

Fix #13 
@giuseppe PTAL
Maybe we could use `MSG_NOSIGNAL` instead.

ignore SIGPIPE

---

.gitattributes
Makefile.am
main.c

This is an alternative to #34 and fixes #22.
* all commit hash definition logic is done in a subshell in the makefile
* both the makefile shell and preprocessor directives in `main.c` fallback to `unknown` if the git command fails or `VERSION` is somehow undefined during compilation
* the subshell uses `git describe` output when building from a checked-out repository or an inserted commit hash when building from a git-archive (i.e. a downloaded tarball)
* [lines 71-74](https://github.com/rootless-containers/slirp4netns/blob/e9dddfb60966e6dd971631e3cda0fdd6403d8d75/Makefile.am#L71) should be reusable for other projects and languages

include commit hash in status output

---

main.c

version: hardcode argv0 for runc compatibility

---

configure.ac

This PR bumps up the hard-coded version string in `configure.ac`. ("v0.2.0" for tagging `v0.2.0`, "v0.2.0+dev" for the next version development)
The PR is a temporary workaround until the discussion on #44 and #45 settles.

Release v0.2.0

---

Dockerfile.tests
Makefile.am
README.md
api.c
api.h
benchmarks/benchmark-iperf3-reverse.sh
main.c
parson/LICENSE
parson/README.md
parson/parson.c
parson/parson.h
qemu/slirp/slirp.c
qemu/slirp/tcp.h
qemu/slirp/tcp_input.c
qemu/slirp/tcp_subr.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/common.sh
tests/test-slirp4netns-api-socket.sh

Now slirp4netns can listen on an UNIX socket for the [QMP](https://wiki.qemu.org/Documentation/QMP)-like API.
```console
$ slirp4netns --api-socket /tmp/slirp4netns.sock ...
```
```console
$ json='{"execute": "add_hostfwd", "arguments": {"proto": "tcp", "host_addr": "0.0.0.0", "host_port": 8080, "guest_addr": "10.0.2.100", "guest_port": 80}}'
$ echo -n $json | nc -U /tmp/slirp4netns.sock
{"return": {"id": 42}}
```
```console
$ json='{"execute": "list_hostfwd"}'
$ echo -n $json | nc -U /tmp/slirp4netns.sock
{"return": {"entries": [{"id": 42, "proto": "tcp", "host_addr": "0.0.0.0", "host_port": 8080, "guest_addr": "10.0.2.100", "guest_port": 80}]}}
```
```console
$ json='{"execute": "remove_hostfwd", "arguments": {"id": 42}}'
$ echo -n $json | nc -U /tmp/slirp4netns.sock
{"return": {}}
``` …

[EXPERIMENTAL] QMP-like JSON API for exposing node ports

---

Makefile.am
main.c
qemu/README.md
qemu/slirp/ip_icmp.c
qemu/slirp/libslirp.h
qemu/slirp/slirp.c
qemu/slirp/slirp.h
qemu/slirp/socket.c
qemu/slirp/socket.h
qemu/slirp/tcp_subr.c
rd235_libslirp/src/qemu2libslirp-bool.h
rd235_libslirp/src/qemu2libslirp.h
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns-no-host-loopback.sh

By default, ports listening on INADDR_LOOPBACK (127.0.0.1) on the host are
accessible from the child namespace via 10.0.2.2.
A new option --no-host-loopback can be used to prohibit connecting to
INADDR_LOOPBACK on the host.
Fix #11 

[security enhancement] add --no-host-loopback

---

Makefile.am
main.c
qemu/slirp/slirp.h
rd235_libslirp/src/qemu2libslirp-bool.h

replace `typedef int bool` with stdbool.h

---

configure.ac
slirp4netns.1
slirp4netns.1.md

Notable changes since v0.2.0:
* [EXPERIMENTAL] QMP-like JSON API for exposing node ports (`--api-socket`) (#29)
*  Support protecting 127.0.0.1 on the host (`--disable-host-loopback`) (#50, #63)
* Support specifying CIDR like `10.0.2.0/24`(`--cidr`) (#62)

Release v0.3.0-alpha.0

---

README.md
configure.ac
qemu/slirp/tcp_subr.c

https://access.redhat.com/security/cve/cve-2019-6778
https://github.com/qemu/qemu/commit/a7104eda7dab99d0cdbd3595c211864cba415905

v0.3.0-alpha.2 (CVE-2019-6778)

---

api.c
configure.ac

Changes since alpha 2:
#72 update docs 
#73 sync with qemu upstream (**NEW BUILD DEPENDENCY**: `glib2-devel` (`libglib2.0-dev`))
cc @rootless-containers/slirp4netns-package-maintainers FYI

v0.3.0-beta.0

---

hack/release.sh

This is a port of the same release.sh script used by runc, umoci,
catatonit and a few other projects. The main benefit is that it allows
you to create signed artefacts of your source tree and static binaries
-- which means that distributions can (along with reproducible builds)
show proof-of-origin for the source code they build.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

hack: add release.sh script

---

MAINTAINERS
qemu/README.md
qemu_patches/0001-slirp-add-slirp_initx-SlirpConfig-SlirpCb-void.patch
qemu_patches/0002-slirp-allow-custom-MTU.patch
qemu_patches/0003-slirp-add-disable_host_loopback-prohibit-connections.patch

No affiliation change (NTT).
The former email address will continue to be available for the time
being.
For daily communication, I still prefer to use my gmail.com address.

MAINTAINERS: update Akihiro Suda's email address

---

main.c
slirp4netns.1
slirp4netns.1.md

Allow a network namespace path to be passed instead of a PID by
using the --use-netns-path argument, and passing a path as the
first argument. An optional --userns-path=PATH argument can be
passed that will be supersede the default user namespace path.
Fixes #84
Signed-off-by: Gabi Beyer <Gabrielle.n.beyer@intel.com>

Support specified netns and userns file paths

---

main.c
tests/test-slirp4netns.sh

it is useful if we are already running inside of a user namespace.

slirp4netns: allow to run without --userns-path

---

main.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.c
slirp4netns.h

Previously, --ready-fd was written when the network configuration (-c)
is ready, but at that time the API socket was not ready to use.
Fix #90

defer --ready-fd activation until everything is ready

---

README.md
api.c
api.h
main.c
slirp4netns.c
slirp4netns.h

add SPDX-License-Identifier headers

---

configure.ac

Notable changes since v0.3.0:
* Support specifying netns path (`slirp4netns --netns-type=path PATH TAPNAME`) (#86)
* Support specifying `--userns-path` (#86 )
* Vendor https://gitlab.freedesktop.org/slirp/libslirp (QEMU v4.1+) (#94)

v0.4.0-beta.0

---

main.c

try again to waitpid if the syscall was interrupted.

main: try waitpid again on EINTR

---

main.c

Within configuring the network; set the loopback device to UP by
default.
Fixes: #101
Signed-off-by: gabi beyer <gabrielle.n.beyer@intel.com>

set lookback device to UP by default

---

configure.ac

Notable changes since v0.3.0:
* Support specifying netns path (`slirp4netns --netns-type=path PATH TAPNAME`) (#86)
* Support specifying `--userns-path` (#86 )
* Vendor https://gitlab.freedesktop.org/slirp/libslirp (QEMU v4.1+) (#94)
* Bring loopback device when `--configure` is specified (#99)

v0.4.0-beta.1

---

main.c

clang-tidy seems to hate `strdup(optarg)` in the `while(getopt())` loop.
Fix #112

Fix clang-tidy 8 issues

---

Dockerfile.buildtests
Dockerfile.tests
main.c
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/test-slirp4netns.sh

when running as root, either on the host or in a user namespace, add a
new option --create-sandbox that will create a new mount namespace and
bind mount only /etc and /run so that the network configuration can be
honored.  Everything else won't be accessible.  Also all capabilities
are dropped.

slirp4netns: add new option --create-sandbox

---

configure.ac

Notable changes since v0.3.0:
* Support specifying netns path (`slirp4netns --netns-type=path PATH TAPNAME`) (#86)
* Support specifying `--userns-path` (#86 )
* Vendor https://gitlab.freedesktop.org/slirp/libslirp (QEMU v4.1+) (#94)
* Bring up loopback device when `--configure` is specified (#99)
* Support sandboxing by creating a mount namespace and dropping capabilities except `CAP_NET_BIND_SERVICE` (#105)
**New build dependency**: `libcap-devel` (`libcap-dev`)

v0.4.0-beta.2

---

configure.ac
qemu/README.md
qemu/slirp/src/ip_icmp.c
qemu_patches/0001-slirp-add-slirp_initx-SlirpConfig-SlirpCb-void.patch
qemu_patches/0002-slirp-allow-custom-MTU.patch
qemu_patches/0003-slirp-add-disable_host_loopback-prohibit-connections.patch

Cherry-pick #120 
cc @rootless-containers/slirp4netns-approvers @rootless-containers/slirp4netns-package-maintainers

[release/0.3] ip_icmp.c: fix use-after-free (release v0.3.1)

---

configure.ac
vendor.sh
vendor/README.md
vendor/libslirp/src/bootp.c
vendor/libslirp/src/ip_input.c
vendor/libslirp/src/libslirp.h
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/tcp_subr.c
vendor/libslirp/src/udp.c

https://gitlab.freedesktop.org/slirp/libslirp/compare/30804efc8f80f43d415057f3099c2894b0f947c4...76462e2f16c6fce6856fb914cbef6207d0be4bc5
Now the legacy `tcp_emu()` is disabled

vendor libslirp@76462e2f16c6fce6856fb914cbef6207d0be4bc5 (v0.4.0-beta.3)

---

configure.ac

Notable changes since v0.3.0:
* Support specifying netns path (`slirp4netns --netns-type=path PATH TAPNAME`) (#86)
* Support specifying `--userns-path` (#86 )
* Vendor https://gitlab.freedesktop.org/slirp/libslirp (QEMU v4.1+) (#94)
* Bring up loopback device when `--configure` is specified (#99)
* Support sandboxing by creating a mount namespace (`--enable-sandbox`) (#105 #136 #138 )
* Fix heap overflow (#127, https://gitlab.freedesktop.org/slirp/libslirp/commit/126c04acbabd7ad32c2b018fe10dfac2a3bc1210)
* Support seccomp (`--enable-seccomp`) (#134)
**New build dependencies**
* `libcap-devel` (`libcap-dev`)
* `libseccomp-devel` (`libseccomp-dev`)

v0.4.0-beta.4

---

api.c

Some variables and labels seems unused so I guess they can be removed safely.

Remove unused variables

---

Makefile.am
sandbox.c
tests/slirp4netns-no-unmount.sh
tests/test-slirp4netns.sh

when creating the sandbox, make sure the mounts are marked with
MS_SLAVE so that events are not propagated to other mount namespaces.
Closes: https://github.com/containers/libpod/issues/4113

sandbox: do not propagate mounts to the parent ns

---

api.c
tests/test-slirp4netns-api-socket.sh

api: raise an error if the socket path is too long

---

vendor.sh
vendor/README.md
vendor/libslirp/src/misc.c
vendor/libslirp/src/sbuf.c
vendor/libslirp/src/socket.c

update to libslirp d171af3732a0610a25334b06b77fa547bd677918
I need it for https://gitlab.freedesktop.org/slirp/libslirp/merge_requests/19

vendor: update libslirp

---

configure.ac

Notable changes since v0.4.2:
* api: raise an error if the socket path is too long (#158)
* libslirp: update to v4.1.0: https://gitlab.freedesktop.org/slirp/libslirp/compare/d203c81bc6c861e1671122c3194c21d1a6763641...v4.1.0
* Including the fix for [`libslirp sends RST to app in response to arriving FIN when containerized socket is shutdown() with SHUT_WR`](https://gitlab.freedesktop.org/slirp/libslirp/issues/12)

v0.4.3-beta.0

---

sandbox.c

This fixes issue #161.
By not returning from create_sandbox() when the remount of "/" fails, slirp4netns continues to operate normally instead of exiting.
I tested this setup for a few days and it seems to work fine.

don't return if remount of "/" fails in create_sandbox

---

main.c

```console
$ slirp4netns --version
slirp4netns version 0.4.3+dev
commit: a0b72ba8210552d01c9f7518f615c9d6def7e980
libslirp: 4.2.0
```

add libslirp version to `slirp4netns --version`

---

Dockerfile.buildtests
Dockerfile.tests

Ubuntu 18.04 has meson 0.45 only.
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>

docker: install meson through pip, since libslirp git requires 0.49

---

configure.ac
main.c
vendor.sh
vendor/README.md
vendor/libslirp/src/bootp.c
vendor/libslirp/src/bootp.h
vendor/libslirp/src/dhcpv6.c
vendor/libslirp/src/ip_icmp.c
vendor/libslirp/src/libslirp-version.h
vendor/libslirp/src/libslirp.h
vendor/libslirp/src/misc.c
vendor/libslirp/src/misc.h
vendor/libslirp/src/ncsi.c
vendor/libslirp/src/slirp.c
vendor/libslirp/src/slirp.h
vendor/libslirp/src/socket.c
vendor/libslirp/src/state.c
vendor/libslirp/src/tcp_subr.c
vendor/libslirp/src/tftp.c
vendor/libslirp/src/udp.c
vendor/libslirp/src/util.c
vendor/libslirp/src/util.h
vendor/parson/parson.c
vendor/parson/parson.h

Notable changes since v0.4.3:
* libslirp: update to v4.2.0: https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.2.0/CHANGELOG.md
This release is expected to be the last official release for v0.3.x .

[release/0.3] vendor libslirp v4.2.0 (release slirp4netns v0.3.5)

---

configure.ac

Notable changes since v0.4.3:
* [libslirp](https://gitlab.freedesktop.org/slirp/libslirp) is no longer included in slirp4netns and needs be installed separately. Binary is built using libslirp v4.2.0. https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.2.0/CHANGELOG.md
**New build dependeny**: `libslirp-devel` >= 4.1 (`libslirp-dev`)

v1.0.0-beta.0

---

sandbox.c
slirp4netns.1
slirp4netns.1.md

sandbox: Warn if /etc/resolv.conf is a symlink to a file outside /etc or /run

---

slirp4netns.1
slirp4netns.1.md

This notation corresponds to README.md and SPDX headers.

man: GPL-2.0 -> GPL-2.0-or-later (corresponds to README.md)

---

Dockerfile.buildtests

The libseccomp-static repo seems to have changed.
https://cbs.centos.org/repos/virt7-container-common-candidate/x86_64/os/ (404)
https://www.spinics.net/lists/centos-devel/msg18472.html

 Dockerfile.buildtests: fix buildtest-centos76-static

---

Dockerfile.buildtests

Cherry-pick https://github.com/rootless-containers/slirp4netns/pull/190

[release/0.4] Dockerfile.buildtests: fix buildtest-centos76-static

---

.github/workflows/main.yaml
Dockerfile.buildtests
Dockerfile.tests
configure.ac

Updated static binary artifact to use libslirp v4.3.0: https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.3.0/CHANGELOG.md
Also updated to use CentOS 7 as the build environment.
Fix #196

v1.0.1 (update binary artifact)

---

Makefile.am
main.c
slirp4netns.1.md
slirp4netns.c
slirp4netns.h
tests/common.sh
tests/test-slirp4netns-disable-dns.sh
tests/test-slirp4netns-outbound-addr.sh

Hi, 
This is first draft of changes providing support for configuration v2 and v3 of libslirp.
Fixes #173 
@AkihiroSuda please let me know your thoughts on this. I am not sure about organization of some parts.
E.g.: 
- is it ok to parse outbound addresses in slirp4netns_config_from_options
~~- if we want to print configured outbound address on slirp setup, is it ok to pass original `char *` outbound_addr/6 to `parent` function or is there better way ? (this is not implemented yet)~~

Support v2 and v3 options from libslirp

---

.github/workflows/release.yaml

docker/binfmt is deprecated in favor or linuxkit/binfmt

buildx: use linuxkit/binfmt

---

Makefile.am
seccomparch.h
seccompfilter.c

seccomp: install filter for non-native archs as well

---

configure.ac

Notable changes since v1.0.1:
* Support `--outbound-addr`, `--outbound-addr6`, `--disable-dns` (#200, thanks to @5eraph)
* ARM binaries are now available (#202, #203)
* seccomp: install filter for non-native archs as well (#205)

v1.1.0-beta.2

---

README.md
configure.ac

Notable changes since v1.0.1:
* Experimentally support `--outbound-addr`, `--outbound-addr6`, `--disable-dns` (#200, thanks to @5eraph)
* ARM binaries are now available (#202, #203). The binaries are statically linked with libslirp v4.3.0, using Debian 10.
* seccomp (experimental): install filter for non-native archs as well (#205)
---
v1.1.x takes over from v1.0.x immediately, because v1.1.0 didn't introduce any change other than experimental stuffs.
v0.4.x will be still maintained until Sep 30, 2020.

Release v1.1.0 + Declare v1.0.x EOL 

---

configure.ac
main.c

Cherry pick https://github.com/rootless-containers/slirp4netns/pull/212

v0.4.6 (Fix config_from_options() to correctly enable ipv6)

---

README.md
slirp4netns.1
slirp4netns.1.md

See "Inter-namespace communication" section of the man page for how to allow communication across multiple slirp4netns instances.
Fix #172

update docs (including guide for inter-namespace communication)

---

seccompfilter.c

Fix https://github.com/containers/podman/issues/6922

seccomp: do not fail on error from seccomp_arch_add()

---

main.c

```
$ slirp4netns --version
slirp4netns version 1.1.4+dev
commit: f79964838de52f282d3c9f5116756835bd9c3952
libslirp: 4.3.1
SLIRP_CONFIG_VERSION_MAX: 3
libseccomp: 2.4.3
```

add libseccomp version to `slirp4netns --version`

---

README.md

Users should upgrade slirp4netns to v1.1.x ASAP.
cc @rootless-containers/slirp4netns-approvers @rootless-containers/slirp4netns-package-maintainers

v0.4.x EOL (2020-09-30)

---

.github/workflows/main.yaml
Makefile.am
Vagrantfile
benchmarks/benchmark-iperf3-reverse.sh
benchmarks/benchmark-iperf3.sh
configure.ac
seccompfilter.c
tests/slirp4netns-no-unmount.sh
tests/test-slirp4netns-cidr.sh
tests/test-slirp4netns-seccomp.sh

Supersedes gh-232.
> seccompfilter: Conditional SCMP_ACT_KILL_PROCESS
>
> As before, this only uses SCMP_ACT_KILL_PROCESS for libseccomp versions
> which define it.
> Additionally, it is only used if at run time the kernel reports it as a
> supported action. For this SECCOMP_GET_ACTION_AVAIL must be available
> (supported from Linux 4.14 onward and backported to CentOS 7's kernel)
> and SECCOMP_RET_KILL_PROCESS (Linux 4.14+, but not in CentOS 7).
This also adds/changes the following:
- Add a CentOS 7 VM/Vagrant-based test run for compatibility (regression) testing on older kernels.
- Add a test case for `--enable-seccomp`.
- Small adjustments to allow CI tests to run on CentOS 7, run out of tree, complete faster.

seccompfilter: Use SCMP_ACT_KILL_PROCESS only on compatible kernels

---

.github/workflows/main.yaml
.gitignore
Vagrantfile

VirtualBox itself's slirp 10.0.2.0/24 was conflicting with slirp4netns CIDR
Contains #236

Vagrantfile: change VirtualBox itself's slirp CIDR + Test with libslirp 4.3.1 on CentOS 7

---

Makefile.am
main.c
slirp4netns.1
slirp4netns.1.md
slirp4netns.h
tests/test-slirp4netns-macaddress.sh

Signed-off-by: Brian Koehmstedt <bkoehm@gmail.com>

Add the --macaddress option to specify the MAC address of the tap interface.

---

slirp4netns.1
slirp4netns.1.md

`nsenter -U` without `--preserve-credentials` often fails with an error: `nsenter: setgroups failed: Operation not permitted`

man: nsenter -U -> nsenter -U --preserve-credentials

---

configure.ac
vendor.sh
vendor/README.md
vendor/parson/LICENSE
vendor/parson/README.md
vendor/parson/parson.c
vendor/parson/parson.h

https://github.com/kgabis/parson/compare/70dc239f...2d7b3ddf

parson: update to v1.1.3 + release slirp4netns v1.1.12

---

Dockerfile.artifact
Dockerfile.buildtests
Dockerfile.tests
Vagrantfile
configure.ac
main.c
slirp4netns.1
slirp4netns.1.md

BESS protocol transferrs L2 packets as AF_UNIX SOCK_SEQPACKET .
BESS protocol has been used by the vector network interfaces of User Mode Linux (UML).
```
(terminal 1) $ slirp4netns --target-type=bess /tmp/bess.sock
(terminal 2) $ linux.uml vec0:transport=bess,dst=/tmp/bess.sock,depth=128,gro=1 root=/dev/root rootfstype=hostfs init=/bin/bash mem=2G
(terminal 2: UML)$ ip addr add 10.0.2.100/24 dev vec0
(terminal 2: UML)$ ip link set vec0 up
(terminal 2: UML)$ ip route add default via 10.0.2.2
```
More docs about the User Mode Linux with BESS socket transport: https://www.kernel.org/doc/html/latest/virt/uml/user_mode_linux_howto_v2.html#bess-socket-transport

Support BESS protocol (for UML)

---

main.c

Signed-off-by: Andreas Kohn <andreas.kohn@gmail.com>

Fix typo in warning message for `--outbound-addr` and `--outbound-addr6`

---

.github/workflows/release.yaml
Dockerfile.buildtests
Dockerfile.tests
Vagrantfile
sandbox.c

Previously if resolv.conf was symlinked to a location other than /etc, or /run, a warning message would be printed and DNS would be non-functional.
Instead, attempt to bind an equivalent resolv.conf link target path in the namespace structure, so that symlink continues to function, and DNS remains operational.
This fixes usage in WSL environments which symlinks /etc/resolv.conf under a shared location under /mnt. Although I suspect this usage pattern is fairly common in other environments. 
Alternatively, instead of mirroring the target path,  this could have utilized the newer open_tree/move_mount syscalls, to bind mount on top of the /etc/resolv.conf symlink. However, this would have limited the support to 5.2 kernels and later, so just cloning the target seemed the way to go. 
Note: …

Add support for escaping resolv.conf symlinks

---

.github/workflows/release.yaml

As part of my last PR, this was pulled in as part of the buildx setup updates to fix the release job, but was not strictly necessary.
(The primary original issue was buildx tripping over other directories created by other processes in it's output path (/tmp)that it didn't have permission to access)

CI: Re-remove usage of qemu-setup-action

---

.github/workflows/release.yaml
Dockerfile.artifact

Binaries should be reproducible with:
```bash
docker buildx build \
-o /tmp/slirpbuilds \
--build-arg SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) \
--platform=amd64,arm64,arm,s390x,ppc64le,riscv64 \
-f Dockerfile.artifact .
```

Enable reproducible builds

---

api.c
main.c

more information in each commit message.
Found by static analysis.

fix some FDs leaks

---

main.c

There seems to be a socket leak in case of success in configure_network() function. This simple patch fixes this.

Do not leak socket in case of success.

---

main.c
slirp4netns.1

The new value tapfd enables removing slirp4netns features. Rather than having it figure out where to create a tap network, the opened tap file descriptor can now be inherited to slirp4netns and used as is. This removes the need for forking and attaching a namespace as well as readiness communication, but it also removes the ability to choose the name of the network interface or configuring it.

Support new --netns-type=tapfd
